import socket

HOST = "127.0.0.1"   # Servidor
PORT = 65123         # Puerto de envio

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST,PORT))
    print("\n-----------------------------------------------------")
    print("Bienvendo a nuestra base de datos de recursos humanos")
    print("-----------------------------------------------------")
    print("\n")
    aux = 1
    empleado = []
    print("Indique que desea realizar: ")
    print("1. Insertar un empleado en la base de datos")
    print("2. Actualizar los datos de un empleado en la base de datos")
    print("3. Hacer una consulta de un empleado en la base de datos")
    print("4. Borrar un empleado en la base de datos\n")
    opcion = input("Seleccione el numero a la opcion correspondiente: ")
    print(opcion)
    message = opcion.encode("utf-8")
    s.sendall(message)   
    print("-----------------------------------------------------\n")
    if(opcion == "1"):   
        print("-----------------------------------------------------")
        print("FAVOR RESPONDER EN MINUSCULAS")
        print("-----------------------------------------------------\n")
        primer_nombre = input("Ingrese el primer nombre del empleado: ")
        message = primer_nombre.encode("utf-8")
        s.sendall(message)   
        segundo_nombre = input("Ingrese el segundo nombre del empleado: ")
        message = segundo_nombre.encode("utf-8")
        s.sendall(message)  
        email = input("Ingrese el email del empleado (solo hotmail.com, si su correo es example@hotmail.com, solo colocar example): ")
        message = email.encode("utf-8")
        s.sendall(message)  
        fecha_nacimiento = input("Ingrese la fecha de nacimiento en el siguiente formato (DDMMAA: 23072002): ")
        message = fecha_nacimiento.encode("utf-8")
        s.sendall(message)  
        sueldo = input("Ingrese el sueldo del empleado: ")
        message = sueldo.encode("utf-8")
        s.sendall(message)  
        comision = input("Ingrese la comisión del empleado: ")
        message = comision.encode("utf-8")
        s.sendall(message)  
        print("\nRevise el cargo del empleado y responda con el numero correspondiente: ")
        print("1. Asistente")
        print("2. Gerente")
        print("3. Aspirante")
        print("4. Supervisor")
        print("5. Control")
        cargo = input("Ingrese el cargo del empleado: ")
        message = cargo.encode("utf-8")
        s.sendall(message)  
        print("\nRevise el departamento del empleado y responda con el numero correspondiente: ")
        print("1. Tecnico")
        print("2. Humanos")
        print("3. Administrativo")
        print("4. Limpieza")
        print("5. Mantenimiento")
        departamento = input("Ingrese el departamento del empleado: ")
        message = departamento.encode("utf-8")
        s.sendall(message)   
    elif(opcion == "2"):
        print("-----------------------------------------------------")
        print("FAVOR RESPONDER EN MINUSCULAS")
        print("-----------------------------------------------------\n")
        id_actualizar = input("Ingrese el ID del empleado: ")
        message = id_actualizar.encode("utf-8")
        s.sendall(message)   
        primer_nombre = input("Ingrese el primer nombre del empleado: ")
        message = primer_nombre.encode("utf-8")
        s.sendall(message)   
        segundo_nombre = input("Ingrese el segundo nombre del empleado: ")
        message = segundo_nombre.encode("utf-8")
        s.sendall(message)  
        email = input("Ingrese el email del empleado (solo hotmail.com, si su correo es example@hotmail.com, solo colocar example): ")
        message = email.encode("utf-8")
        s.sendall(message)  
        fecha_nacimiento = input("Ingrese la fecha de nacimiento en el siguiente formato (DDMMAA: 23072002): ")
        message = fecha_nacimiento.encode("utf-8")
        s.sendall(message)
        sueldo = input("Ingrese el sueldo del empleado: ")
        message = sueldo.encode("utf-8")
        s.sendall(message)  
        comision = input("Ingrese la comisión del empleado: ")
        message = comision.encode("utf-8")
        s.sendall(message)  
        print("\nRevise el cargo del empleado y responda con el numero correspondiente: ")
        print("1. Asistente")
        print("2. Gerente")
        print("3. Aspirante")
        print("4. Supervisor")
        print("5. Control")
        cargo = input("Ingrese el cargo del empleado: ")
        message = cargo.encode("utf-8")
        s.sendall(message)  
        print("\nRevise el departamento del empleado y responda con el numero correspondiente: ")
        print("1. Tecnico")
        print("2. Humanos")
        print("3. Administrativo")
        print("4. Limpieza")
        print("5. Mantenimiento")
        departamento = input("Ingrese el departamento del empleado: ")
        message = departamento.encode("utf-8")
        s.sendall(message)   
    elif(opcion == "3"):
        id_consulta = input("Ingrese el ID de la persona a consultar: ")
        message = id_consulta.encode("utf-8")
        s.sendall(message)   
    elif(opcion == "4"):
        id_eliminar = input("Ingrese el ID de la persona a eliminar: ")
        message = id_eliminar.encode("utf-8")
        s.sendall(message)  
    else:
        print("Oops, hubo un error")

    data = s.recv(1024)
    print(data)
    

